INSERT INTO products (product_name, product_description, price, stock_quantity) 
VALUES 
('Dell XPS 13', 'The Dell XPS 13 is a high-performance laptop that features an ultra-thin design, offering both portability and power. It comes with a 13.4-inch InfinityEdge display, Intel Core i7 processor, 16GB of RAM, and a 512GB SSD, making it perfect for professionals and creatives alike. The XPS 13 also includes long battery life, fast charging, and a sleek aluminum body for durability and style.', 1199.99, 50),
('Apple MacBook Pro 16"', 'The Apple MacBook Pro 16-inch is the ultimate machine for creative professionals and power users. It boasts a stunning Retina display, the latest Apple M1 Pro or M1 Max chip, and up to 64GB of RAM. With a massive 1TB SSD, this laptop can handle intensive tasks such as video editing, 3D rendering, and software development. The new Magic Keyboard, advanced cooling system, and long battery life make it a dream for any tech enthusiast.', 2499.99, 30),
('HP Spectre x360', 'The HP Spectre x360 is a versatile 2-in-1 convertible laptop that offers the flexibility of a tablet and the performance of a laptop. With a 13.3-inch 4K AMOLED touchscreen, Intel Core i7 processor, and 16GB of RAM, this laptop is perfect for multitasking, content creation, and entertainment. The Spectre x360 is known for its stunning design, high-quality build, and impressive battery life.', 1399.99, 45),
('Lenovo ThinkPad X1 Carbon', 'The Lenovo ThinkPad X1 Carbon is a premium ultrabook designed for business professionals who demand performance, durability, and security. It features a 14-inch FHD or UHD display, Intel Core i7 or i9 processors, and up to 32GB of RAM. The X1 Carbon has a lightweight carbon fiber chassis, long battery life, and military-grade durability, making it an ideal choice for those on the go.', 1699.99, 40),
('Asus ROG Zephyrus G14', 'The Asus ROG Zephyrus G14 is a gaming laptop that combines performance and portability. Equipped with an AMD Ryzen 9 processor and NVIDIA GeForce RTX 3060 or 3070 graphics, this laptop can handle even the most demanding games and applications. The 14-inch 120Hz display, long battery life, and compact design make it the perfect choice for gamers who need power on the move.', 1599.99, 20),
('Microsoft Surface Laptop 4', 'The Microsoft Surface Laptop 4 offers a beautiful PixelSense display, powerful performance, and an ultra-slim design. With Intel Core i5 or i7 processors, 8GB or 16GB of RAM, and up to 1TB SSD, this laptop is ideal for work, study, and casual entertainment. Its clean and minimalist design, along with excellent keyboard and trackpad, make it a favorite among those who value both style and substance.', 1299.99, 60),
('Acer Predator Helios 300', 'The Acer Predator Helios 300 is a high-performance gaming laptop that offers excellent value for money. It features an Intel Core i7 processor, NVIDIA GeForce RTX 3060 or 3070 graphics, and a 15.6-inch 144Hz Full HD display. With 16GB of RAM and a 512GB SSD, this laptop is designed for gamers who want a smooth and immersive gaming experience without breaking the bank.', 1499.99, 25),
('Samsung Galaxy Book Pro 360', 'The Samsung Galaxy Book Pro 360 is a sleek, lightweight 2-in-1 laptop with a 13.3-inch AMOLED touchscreen display. Powered by an Intel Core i7 processor, 8GB of RAM, and a 512GB SSD, this laptop offers excellent performance for everyday tasks, entertainment, and creativity. The 360-degree hinge allows it to be used as a tablet, making it an incredibly versatile device for professionals and students alike.', 1399.99, 35),
('Razer Blade 15', 'The Razer Blade 15 is a premium gaming laptop designed for gamers and content creators. With an Intel Core i7 processor, NVIDIA GeForce RTX 3070 or 3080 graphics, and a 15.6-inch 144Hz or 360Hz display, it delivers top-tier gaming performance. Its slim, sleek aluminum chassis houses up to 32GB of RAM and a 1TB SSD, making it an excellent choice for high-performance tasks and gaming on the go.', 1999.99, 15),
('MSI Prestige 14', 'The MSI Prestige 14 is a stylish and powerful laptop designed for professionals who need portability and performance. Featuring a 14-inch 4K display, Intel Core i7 processor, 16GB of RAM, and a 512GB SSD, the Prestige 14 excels in creative work like video editing, graphic design, and 3D modeling. With a slim design, long battery life, and lightweight build, it’s perfect for on-the-go productivity.', 1499.99, 30);
